import '../lib/fzf.just'

# show available recipes
default:
    @just --list

# private: raw volume listing (with links + size) for fzf
_ls:
    @docker system df -v | sed -n '/VOLUME NAME/,/^$/ { p }' | sed 1d

# private: select volume(s), print name + links + size columns
_pick *flags:
    @just _ls | just _fzf 'rm rmf inspect' {{flags}}

# remove selected volume(s)
rm:
    @just _pick | while read -r name _; do docker volume rm "$name"; done

# force-remove selected volume(s)
rmf:
    @just _pick | while read -r name _; do docker volume rm -f "$name"; done

# inspect selected volume(s)
inspect:
    @just _pick | while read -r name _; do docker volume inspect "$name"; done
